server:
  port: 8081
 # DataSource Config
spring:
  datasource:
    drver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueadmin?useUnicode=ture&useSSL=false&characterEncodeing=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#  security:
#    user:
#      name: user
#      password: 111111
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
markerhub:
  jwt:
    header: Authorization
    expire: 604800    #7天 换算 秒
    secret: asd67dasjdhasdasd78966asd76d222a
